---
kind: pipeline
type: kubernetes
name: OpsData-golang-amd64

platform:
  os: linux
  arch: amd64

steps:

  - name: Docker-Build-DryRun
    image: plugins/docker
    settings:
      purge: false
      registry: a1-harbor.support.tools
      repo: a1-harbor.support.tools/opsdata/golang
      dockerfile: ./Dockerfile
      dry_run: true
      context: ./
      tags:
        - ${DRONE_BUILD_NUMBER}
        - ${DRONE_COMMIT_BRANCH}
        - latest

  - name: Docker-Build-Publish-to-Harbor
    image: plugins/docker
    settings:
      purge: false
      registry: a1-harbor.support.tools
      repo: a1-harbor.support.tools/opsdata/golang
      dockerfile: ./Dockerfile
      dry_run: false
      context: ./
      tags:
        - ${DRONE_BUILD_NUMBER}
        - ${DRONE_COMMIT_BRANCH}
        - latest
      cache_from: "a1-harbor.support.tools/opsdata/golang:latest"
      username:
        from_secret: harbor-username
      password:
        from_secret: harbor-password
    when:
     event:
     - deployment
     - promote
     target:
     - production

  - name: Docker-Build-Publish-to-DockerHub
    image: plugins/docker
    settings:
      custom_dns: [ 1.1.1.1, 1.0.0.1 ]
      purge: false
      registry: docker.io
      repo: docker.io/cube8021/golang
      dockerfile: ./Dockerfile
      dry_run: false
      context: ./
      tags:
        - ${DRONE_BUILD_NUMBER}
        - ${DRONE_COMMIT_BRANCH}
        - latest
      cache_from: "a1-harbor.support.tools/opsdata/golang:latest"
      username:
        from_secret: docker-username
      password:
        from_secret: docker-password
    when:
     event:
     - deployment
     - promote
     target:
     - production

node_selector:
  beta.kubernetes.io/arch: amd64
  drone-runner: true

image_pull_secrets:
- regcreds

---
kind: pipeline
type: kubernetes
name: OpsData-golang-arm64

platform:
  os: linux
  arch: arm64

steps:

  - name: Docker-Build-DryRun
    image: plugins/docker
    settings:
      custom_dns: [ 1.1.1.1, 1.0.0.1 ]
      purge: false
      registry: a1-harbor.support.tools
      repo: a1-harbor.support.tools/opsdata/golang
      dockerfile: ./Dockerfile
      dry_run: true
      context: ./
      tags:
        - ${DRONE_BUILD_NUMBER}
        - ${DRONE_COMMIT_BRANCH}
        - latest

  - name: Docker-Build-Publish-to-Harbor
    image: plugins/docker
    settings:
      custom_dns: [ 1.1.1.1, 1.0.0.1 ]
      purge: false
      registry: a1-harbor.support.tools
      repo: a1-harbor.support.tools/opsdata/golang
      dockerfile: ./Dockerfile
      dry_run: false
      context: ./
      tags:
        - ${DRONE_BUILD_NUMBER}
        - ${DRONE_COMMIT_BRANCH}
        - latest
      cache_from: "a1-harbor.support.tools/opsdata/golang:latest"
      username:
        from_secret: harbor-username
      password:
        from_secret: harbor-password
    when:
     event:
     - deployment
     - promote
     target:
     - production

  - name: Docker-Build-Publish-to-DockerHub
    image: plugins/docker
    settings:
      custom_dns: [ 1.1.1.1, 1.0.0.1 ]
      purge: false
      registry: docker.io
      repo: docker.io/cube8021/golang
      dockerfile: ./Dockerfile
      dry_run: false
      context: ./
      tags:
        - ${DRONE_BUILD_NUMBER}
        - ${DRONE_COMMIT_BRANCH}
        - latest
      cache_from: "a1-harbor.support.tools/opsdata/golang:latest"
      username:
        from_secret: docker-username
      password:
        from_secret: docker-password
    when:
     event:
     - deployment
     - promote
     target:
     - production

node_selector:
  beta.kubernetes.io/arch: arm64
  drone-runner: true

image_pull_secrets:
- regcreds